[package]
name = "swayex"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = "1.0.81"
log = "0.4.17"
env_logger = "0.9.0"
anyhow = "1.0.57"

serde = { version = "1.0.137", features = ["derive"] }
